# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='answers_given',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_no',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
