# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0002_auto_20170827_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='number',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='solution',
        ),
    ]
