# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0003_auto_20170828_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
    ]
