# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0004_auto_20170828_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='question_no',
            new_name='question_no1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_no2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_no3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='answers_given',
            field=models.CharField(default='000000000000000000', max_length=100),
        ),
    ]
