# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans', '0005_auto_20170910_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='question_no4',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_no5',
            field=models.IntegerField(default=1),
        ),
    ]
